### ISSUE TITLE
iOS supported version check is wrong

### ISSUE THREAD

**Issue by NicolaVerbeeck** [icapps/flutter_secure_file_storage#5] opened 2021-12-19 18:50 UTC
It just checks != 12 so it would also match below 12!

**Comment by ikbendewilliam** [comment] 2021-12-20 08:41
Correct, we only check version 12 for our app, since it's the only < 13 iOS version that is supported. But the package should also check 8-11

**Comment by ikbendewilliam** [comment] 2021-12-20 08:42
see also #3

**Comment by vanlooverenkoen** [comment] 2022-10-14 12:02
duplicate of #3

**Closed by vanlooverenkoen** 2022-10-14 12:03 UTC
Labels: bug, P0
